<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="CsCheck" Version="4.1.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Testcontainers.MsSql" Version="4.3.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\POS.Domain\POS.Domain.csproj" />
    <ProjectReference Include="..\..\src\POS.Application\POS.Application.csproj" />
    <ProjectReference Include="..\..\src\POS.Infrastructure\POS.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\POS.Presentation\POS.Presentation.csproj" />
  </ItemGroup>

</Project>
